version: 0.2

env:
  variables:
    x: y

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y xsltproc
      - git clone https://github.com/rubys/venus.git
  pre_build:
    commands:
      - aws s3 cp s3://planet-if.com/cache.tar.gz cache.tar.gz || echo "no cache"
      - tar xzf cache.tar.gz || echo "no cache"
  build:
    commands:
      - python venus/planet.py planet-if.conf
  post_build:
    commands:
      - tar czf cache.tar.gz cache
      - aws s3 cp cache.tar.gz s3://planet-if.com
      - aws s3 cp --recursive output s3://planet-if.com
