version: 0.2

env:
  variables:
    x: y

phases:
  install:
    commands:
      - git clone https://github.com/rubys/venus.git
  build:
    commands:
      - python venus/planet.py planet-if.conf
  post_build:
    commands:
      - aws s3 cp --recursive output s3://planet-if

# artifacts:
#   files:
#     - output/*
#   discard-paths: yes
