version: 0.2

env:
  variables:
    x: y

phases:
  install:
    commands:
      - git clone https://github.com/rubys/venus.git
  pre_build:
    commands:
      - aws s3 cp s3://planet-if/cache.tar.gz
      - tar xzf cache.tar.gz
  build:
    commands:
      - python venus/planet.py planet-if.conf
  post_build:
    commands:
      - tar czf cache.tar.gz cache
      - aws s3 cp cache.tar.gz s3://planet-if
      - aws s3 cp --recursive output s3://planet-if
