version: 0.2

env:
  variables:
    x: y

phases:
  install:
    commands:
      - git clone https://github.com/rubys/venus.git
  build:
    commands:
      - echo "hello" > output/index.html
  post_build:
    commands:
      - aws cp output/* s3://planet-if

# artifacts:
#   files:
#     - output/*
#   discard-paths: yes
